### PR TITLE
update owner information

### PR DESCRIPTION
**Pull request by mulby**
@edx/rev-team FYI

Updating ownership information to be compliant with the newly revised OEP-2

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@natabene I'm reviewing this tiny PR so I've added the `cc-reviewer` tag.

**Comment by OmarIthawi** [comment]
Hi @mulby. I'd like to review this PR. As you might have heard the [Core Committers program is now on Phase 1](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers) and I'm starting with the `edx-ace` repository. 

It sounds like a good small PR, could you please rebase to resolve conflicts? I see that the `openedx.yaml` have been updated and we have conflicts.

**Comment by mulby** [comment]
Hi @OmarIthawi -- excited to have you helping out on this repo. We decided to move away from documenting ownership in openedx.yaml, however, so this PR is now obsolete. I'm going to close it.

**Comment by aekao** [comment]
Hey all, speaking of documenting ownership, could I be removed from @edx/rev-team team? I'm suddenly getting notifications from this tag, but couldn't see where to remove myself. I left edX around April 2019.

**Comment by mulby** [comment]
Hi @aekao - I've confirmed you aren't on the edx/rev-team github team anymore, maybe github remembers that you were when the tag was used?

**Comment by aekao** [comment]
Weird, ok thanks for checking!

**Pull request closed without merging**
